#
# Makefile
#
# Copyright (c) 2020-2020 Huawei Technologies Co., Ltd.
#
# laser st common makefile
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ccflags-y += -I$(src)/vl53L1/inc -I$(src)/vl53L1/src \
			-I$(src)/vl53L1/protected -I$(src)/vl53L1/protected/inc \
			-I$(src)/vl53L1 -I$(src)
obj-y += vl53L1/
obj-y += laser_module.o
