#
# Makefile for misc devices that really don't fit anywhere else.
#
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw01624/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw86907/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw8697/
obj-$(CONFIG_HUAWEI_HIGH_VOLT_VIBRATOR) += high_vib/