subdir-ccflags-y += -Werror -I$(srctree)/drivers/power/supply/mediatek/charger
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc/
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
obj-$(CONFIG_ETA6937_CHARGER) += eta_charger_mtk.o
