/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2018-2020. All rights reserved.
 * Description: this file is used to adapt oeminfo_v6 id to oeminfo_lite for being compatible with OEMINFO_VERSION6
 * Author: wangyukai
 * Create: 2018-7-18
 */

#ifndef INCLUDE_OEMINFO_V6_TO_LITE_H
#define INCLUDE_OEMINFO_V6_TO_LITE_H
#define OEMINFO_UNUSEED_TYPE_USER_LITE_1      0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_3      0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_5      0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_7      0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_19     0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_21     0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_23     0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_201    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_210    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_210    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_213    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_216    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_219    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_222    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_225    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_228    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_231    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_234    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_237    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_240    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_243    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_246    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_249    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_252    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_255    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_258    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_261    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_264    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_267    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_270    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_273    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_276    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_279    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_282    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_285    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_288    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_290    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_292    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_295    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_298    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_319    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_322    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_332    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_335    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_338    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_341    0
#define OEMINFO_UNUSEED_TYPE_USER_LITE_344    0

typedef enum {
    /* the next id is used for oeminfo_lite none-wp area */
    OEMINFO_NONEWP_AMSS_VER_TYPE_LITE = 1,
    OEMINFO_NONEWP_OEMSBL_VER_TYPE_LITE = 2,
    OEMINFO_NONEWP_UPDATE_TYPE_LITE = 3,
    OEMINFO_NONEWP_WIFI_TEST_LITE = 4,
    OEMINFO_NONEWP_HWSB_LOCK_STATE_LITE = 5,
    OEMINFO_NONEWP_HWFB_LOCK_STATE_LITE = 6,
    OEMINFO_NONEWP_USER_USAGE_ACTIVDATE_TYPE_LITE = 7,
    OEMINFO_NONEWP_USB_PID_INDEX_LITE = 8,
    OEMINFO_NONEWP_USB_PID_CUSTOM_TYPE_LITE = 9,
    OEMINFO_NONEWP_TPCOLOR_TYPE_LITE = 10,
    OEMINFO_NONEWP_CRYPTFS_STATE_LITE = 11,
    OEMINFO_NONEWP_ROOT_INFO_TYPE_LITE = 12,
    OEMINFO_NONEWP_RESCUEINFO_TYPE_LITE =  13,
    OEMINFO_NONEWP_CAEMRA_DF_TYPE_LITE = 14,
    OEMINFO_NONEWP_CAMERA_HALL_OVERTURN_DATA_LITE = 15,
    OEMINFO_NONEWP_AT_LOCK_PASSWORD_SHA256_LITE = 16,
    OEMINFO_NONEWP_DAP_TIME_LITE = 17,
    OEMINFO_NONEWP_PSID_DATA_LITE = 18,
    OEMINFO_NONEWP_RESOURCE_VERSION_LITE = 19,
    OEMINFO_NONEWP_CRYPTFS_DATA_LITE = 20,
    OEMINFO_NONEWP_INITRC_TRACER_LITE = 21,
    OEMINFO_NONEWP_FBLOCK_STAT_INFO_LITE = 22,
    OEMINFO_NONEWP_VENDER_AND_COUNTRY_NAME_COTA_LITE = 23,
    OEMINFO_NONEWP_ANTITHIVES_STATE_LITE = 24,
    OEMINFO_NONEWP_WIFI_CAL_INDEX_LITE = 25,
    OEMINFO_NONEWP_SD_LOCK_PASSWD_LITE = 26,
    OEMINFO_NONEWP_MAIN_VERSION_LITE = 27,
    OEMINFO_NONEWP_BOOTANIM_SWITCH_LITE = 28,
    OEMINFO_NONEWP_BOOTANIM_SHUTFLAG_LITE = 29,
    OEMINFO_NONEWP_BOOTANIM_RINGMODE_LITE = 30,
    OEMINFO_NONEWP_BOOTANIM_RINGDEX_LITE = 31,
    OEMINFO_NONEWP_DATA_PART_FAULT_TIMES_LITE = 32,
    OEMINFO_NONEWP_APPS_NO_INSTALL_TYPE_LITE = 33,
    OEMINFO_NONEWP_SYSTEM_VERSION_LITE = 34,
    OEMINFO_NONEWP_GAMMA_DATA_LITE = 35,
    OEMINFO_NONEWP_GAMMA_LEN_LITE = 36,
    OEMINFO_NONEWP_MCC_MNC_TYPE_LITE = 37,
    OEMINFO_NONEWP_OPERATOR_INFO_LITE = 38,
    OEMINFO_NONEWP_HOTA_UPDATE_AUTH_LOCK_LITE = 39,
    OEMINFO_NONEWP_FACTORY_PRODUCT_VERSION_TYPE_LITE = 40,
    OEMINFO_NONEWP_AUDIO_SMARTPA_CALIBRATION_LITE = 41,
    OEMINFO_NONEWP_WIFIONLY_IDENTITY_LITE = 42,
    OEMINFO_NONEWP_LCD_BRIGHT_COLOR_CALIBRATION_LITE = 43,
    OEMINFO_NONEWP_FOTA_MODE_LITE = 44,
    OEMINFO_NONEWP_MARKETING_NAME_LITE = 45,
    OEMINFO_NONEWP_OVMODE_STATE_LITE = 46,
    OEMINFO_NONEWP_OMADM_INFO_LITE = 47,
    OEMINFO_NONEWP_ACTIVATION_STATUS_ID_LITE = 48,
    OEMINFO_NONEWP_HWPARENTCONTROL_RECOVER_DATA_LITE = 49,
    OEMINFO_NONEWP_FIX_HOTA_INFO_INTI_LITE = 50,
    OEMINFO_NONEWP_FIX_HOTA_INFO_LITE = 51,
    OEMINFO_NONEWP_FIX_HOTA_STRING_INTI_LITE = 52,
    OEMINFO_NONEWP_FIX_HOTA_STRING_LITE = 53,
    OEMINFO_NONEWP_VENDER_AND_COUNTRY_NAME_COTA_FACTORY_LITE = 54,
    OEMINFO_NONEWP_USER_HOTA_UPDATE_LITE = 55,
    OEMINFO_NONEWP_USE_DECRESS_BAT_VOL_FLAG_LITE = 56,
    OEMINFO_NONEWP_UPDATE_UDID_LITE = 57,
    OEMINFO_NONEWP_FACTORY_SW_VERSION_LITE = 58,
    OEMINFO_NONEWP_PRELOAD_APP_BATCH_LITE = 59,
    OEMINFO_NONEWP_CUST_Y_CABLE_TYPE_LITE = 60,
    OEMINFO_NONEWP_SDUPDATE_TYPE_LITE = 61,
    OEMINFO_NONEWP_ENABLE_RETREAD_LITE = 62,
    OEMINFO_NONEWP_SYSTEM_UPDATE_AUTH_TOKEN_INFO_LITE = 63,
    OEMINFO_NONEWP_ENCRYPT_INFO_LITE = 64,
    OEMINFO_NONEWP_MALWARE_DIAGNOSE_LITE = 65,
    OEMINFO_NONEWP_RETREAD_DIAGNOSE_LITE = 66,
    OEMINFO_NONEWP_ROOT_DIAGNOSE_LITE = 67,
    OEMINFO_NONEWP_SYSTEM_VERSION_B_LITE = 68,
    OEMINFO_NONEWP_ANDROID_VERSION_LITE = 69,
    OEMINFO_NONEWP_ANDROID_VERSION_B_LITE = 70,
    OEMINFO_NONEWP_SLOT_INFO_A_LITE = 71,
    OEMINFO_NONEWP_SLOT_INFO_B_LITE = 72,
    OEMINFO_NONEWP_SLOT_STATUS_LITE = 73,
    OEMINFO_NONEWP_VERITY_MODE_UPDATE_STATUS_LITE = 74,
    OEMINFO_NONEWP_SYSTEM_UPDATE_STATE_LITE = 75,
    OEMINFO_NONEWP_BASE_VER_TYPE_LITE  = 76,
    OEMINFO_NONEWP_CUST_VER_TYPE_LITE =  77,
    OEMINFO_NONEWP_PRELOAD_VER_TYPE_LITE = 78,
    OEMINFO_NONEWP_CUSTOM_VERSION_LITE = 80,
    OEMINFO_NONEWP_CUSTOM_VERSION_B_LITE = 81,
    OEMINFO_NONEWP_PRELOAD_VERSION_LITE = 82,
    OEMINFO_NONEWP_PRELOAD_VERSION_B_LITE = 83,
    OEMINFO_NONEWP_GROUP_VERSION_LITE = 84,
    OEMINFO_NONEWP_GROUP_VERSION_B_LITE = 85,
    OEMINFO_NONEWP_BASE_VERSION_LITE = 86,
    OEMINFO_NONEWP_BASE_VERSION_B_LITE = 87,
    OEMINFO_NONEWP_BDRT_TYPE_LITE = 89,
    OEMINFO_NONEWP_COTA_REBOOT_UPDATE_PATH_LITE = 90,
    OEMINFO_NONEWP_CUSTOM_C_VERSION_LITE = 91,
    OEMINFO_NONEWP_RUNTEST_TYPE_LITE = 92,
    OEMINFO_NONEWP_MMITEST_TYPE_LITE = 93,
    OEMINFO_NONEWP_OTA_SIMLOCK_ACTIVATED_LITE = 94,
    OEMINFO_NONEWP_ATLOCK_TYPE_LITE = 95,
    OEMINFO_NONEWP_RUNTEST2_TYPE_LITE = 96,
    OEMINFO_NONEWP_RUNTIME_TYPE_LITE = 97,
    OEMINFO_NONEWP_MDATE_TYPE_LITE = 98,
    OEMINFO_NONEWP_MANUFACTURE_RESET_FLAG_LITE = 99,
    OEMINFO_NONEWP_BACKCOLOR_LITE = 100,
    OEMINFO_NONEWP_FB_STP_TYPE_LITE = 101,
    OEMINFO_NONEWP_RESET_ENTER_INFO_LITE = 102,
    OEMINFO_NONEWP_UPDATE_ENTER_INFO_LITE = 103,
    OEMINFO_NONEWP_RETAIL_APK_LITE = 104,
    OEMINFO_NONEWP_CUST_OVMODE_STATE_LITE = 105,
    OEMINFO_NONEWP_PRELOAD_OVMODE_STATE_LITE = 106,
    OEMINFO_NONEWP_ESIM_EID_LITE = 107,
    OEMINFO_NONEWP_CLOUD_ROM_INSTALL_STAT_LITE = 108,
    OEMINFO_NONEWP_DEV_NG_INFO_LITE = 109,
    OEMINFO_NONEWP_VSIM_WIFIPOLL_FLAG_LITE = 110,
    OEMINFO_NONEWP_VSIM_DOWNLOAD_STATUS_LITE = 111,
    OEMINFO_NONEWP_VSIM_WIFI_CONN_STATUS_LITE = 112,
    OEMINFO_NONEWP_CAMERA_SPECS_LITE = 113,
    OEMINFO_NONEWP_UNBIND_FLAG_LITE = 114,
    OEMINFO_NONEWP_DEBUG_EFUSE_FLAG_LITE = 115,
    OEMINFO_NONEWP_WIFI_COUNTRY_CODE_LITE = 116,
    OEMINFO_NONEWP_CCFLAG_LITE = 117,
    OEMINFO_NONEWP_FACT_ODM_LITE = 118,
    OEMINFO_NONEWP_RUNTESTB_TYPE_LITE = 119,
    OEMINFO_NONEWP_POPUPUSEDCOUNT_LITE = 120,
    OEMINFO_NONEWP_MOTORCODE_LITE = 121,
    OEMINFO_NONEWP_POS_HALL_CALIBRATION_DATA = 122,
    OEMINFO_NONEWP_CUSTOMEI_LITE = 123,
    OEMINFO_NONEWP_SCCAL_CUR_LITE = 124,
    OEMINFO_NONEWP_CUR_OFFSET_LITE = 125,
    OEMINFO_NONEWP_BAT_BLIMSW = 126,
    OEMINFO_NONEWP_BAT_BBINFO = 127,
    OEMINFO_NONEWP_BAT_HWCOUL = 128,
    OEMINFO_NONEWP_PPR = 129,
    OEMINFO_NONEWP_HOTA_BOOT_MODE = 131,
    OEMINFO_NONEWP_POST_CUSTOM_TYPE_LITE = 133,
    OEMINFO_NONEWP_UTAPKAUTORUN = 134,
    /* the id from 500 to 550 of 8k area are reserved */
    OEMINFO_NONEWP_REUSED_ID_551_8K_VALID_SIZE_448_BYTE_LITE = 551,
    OEMINFO_NONEWP_REUSED_ID_552_8K_VALID_SIZE_64_BYTE_LITE = 552,
    OEMINFO_NONEWP_FMD_VERIFY_DATA_LITE = 553,
    OEMINFO_NONEWP_FCDEG_LITE = 554,
    /* the id from 700 to 710 of 64k area are reserved */
    OEMINFO_NONEWP_WCNSS_FIR_BAK_TYPE_LITE = 711,
    OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION1_TYPE_LITE = 712,
    OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION2_TYPE_LITE = 713,
    OEMINFO_NONEWP_FASTBOOT_FMD_DATA_LITE = 714,
    OEMINFO_NONEWP_BASE_CLOUD_ROM_LIST_LITE = 715,
    OEMINFO_NONEWP_CONTROL_MODE_DATA = 716,
    OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION3_TYPE_LITE = 717,
    OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION4_TYPE_LITE = 718,
    OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION5_TYPE_LITE = 719,
    OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION6_TYPE_LITE = 720,
    OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION7_TYPE_LITE = 721,
    OEMINFO_NONEWP_CAMERA_BLC_CALIB_LITE = 722,
    OEMINFO_NONEWP_SPECCALIB0_LITE = 723,
    OEMINFO_NONEWP_SPECCALIB1_LITE = 724,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_00_LITE = 725,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_01_LITE = 726,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_02_LITE = 727,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_03_LITE = 728,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_04_LITE = 729,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_05_LITE = 730,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_06_LITE = 731,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_07_LITE = 732,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_08_LITE = 733,
    OEMINFO_NONEWP_CAMERA_EEPROM_DATA_09_LITE = 734,
    OEMINFO_NONEWP_CGM_SCG_DATA_LITE = 735,
    OEMINFO_NONEWP_CGM_WCG_DATA_LITE = 736,
    /* the next id is used for oeminfo_lite root-wp area */
    OEMINFO_ROOTWP_BOARD_CODE_TYPE_LITE = 751,
    OEMINFO_ROOTWP_VENDER_AND_COUNTRY_NAME_LITE = 752,
    OEMINFO_ROOTWP_IMEI2_NUM_LITE = 753,
    OEMINFO_ROOTWP_FACT_INFO_LITE = 754,
    OEMINFO_ROOTWP_HWSB_AES_PWD_LITE = 755,
    OEMINFO_ROOTWP_SKU_TYPE_LITE = 756,
    OEMINFO_ROOTWP_MANUFACTURE_DATE_TYPE_LITE = 757,
    OEMINFO_ROOTWP_LGU_SPECIAL_SN_LITE = 758,
    OEMINFO_ROOTWP_IMEI_TYPE_LITE = 759,
    OEMINFO_ROOTWP_MEID_TYPE_LITE = 760,
    OEMINFO_ROOTWP_ESN_TYPE_LITE = 761,
    OEMINFO_ROOTWP_BT_TYPE_LITE = 762,
    OEMINFO_ROOTWP_WIFI_TYPE_LITE = 763,
    OEMINFO_ROOTWP_FACTORY_INFO_TYPE_LITE = 764,
    OEMINFO_ROOTWP_BUILD_NUMBER_TYPE_LITE = 766,
    OEMINFO_ROOTWP_SINGLE_SIM_LITE = 767,
    OEMINFO_ROOTWP_PRODUCT_MODEL_TYPE_LITE = 768,
    OEMINFO_ROOTWP_DEVICE_MODEL_LITE = 769,
    OEMINFO_ROOTWP_FRP_OPEN_FLAG_LITE = 770,
    OEMINFO_ROOTWP_FRP_KEY_LITE = 771,
    OEMINFO_ROOTWP_PRODUCE_PHASE_FLAG_LITE = 772,
    OEMINFO_ROOTWP_MMIAUTORUN_LITE = 773,
    OEMINFO_ROOTWP_MMIAUTOCFG_LITE = 774,
    OEMINFO_ROOTWP_RD_LOCK_STATE_LITE = 775,
    OEMINFO_ROOTWP_ACCESS_LOCK_STATE_LITE = 776,
    OEMINFO_ROOTWP_ACCESS_KEY_LITE = 777,
    OEMINFO_ROOTWP_CONTROL_FLAG_LITE = 778,
    OEMINFO_ROOTWP_QRCODE_INFO_LITE = 779,
    OEMINFO_ROOTWP_LOG_SWITCH_TYPE_LITE = 780,
    OEMINFO_ROOTWP_BASEBAND_VERSION_TYPE_LITE = 781,
    OEMINFO_ROOTWP_CONTROL_BIT_LITE = 782,
    OEMINFO_ROOTWP_UDID_CODE_TYPE_LITE = 783,
    OEMINFO_ROOTWP_SYSDLL_INSTALL_TYPE_LITE = 786,
    OEMINFO_ROOTWP_TOF_EYE_SAFE_TYPE_LITE = 789,
    OEMINFO_ROOTWP_AUTH_ELABEL_LITE = 790,
    OEMINFO_ROOTWP_TIME_ON_TYPE = 791,
    OEMINFO_ROOTWP_DDC_TYPE_LITE = 793,

    /* the id from 1250 to 1300 of 8k area are reserved */
    OEMINFO_ROOTWP_DEVICE_CERTIFICATE1_LITE = 1301,
    OEMINFO_ROOTWP_DEVICE_CERTIFICATE2_LITE = 1302,
    OEMINFO_ROOTWP_KEY_ATTESTATION_LITE = 1303,

    /* the id from 1450 to 1460 of 64k area are reserved */
    OEMINFO_ROOTWP_NFC_SEID_LITE = 1461,
    OEMINFO_ROOTWP_SCREEN_DATA_LITE = 1462,
    OEMINFO_ROOTWP_CUST_LOGO_EXTERN = 1463,
    OEMINFO_ROOTWP_POWER_CHARGING_TYPE_EXTERN = 1464,
    OEMINFO_ROOTWP_LOW_POWER_TYPE_EXTERN = 1465,
    OEMINFO_ROOTWP_COLOR_SENSOR_CALI_MATRIX = 1466,

    /* the next id is used for oeminfo_lite powerup-wp area */
    OEMINFO_PWRUPWP_SENSOR_PROXIMITY_PA2240_CALIBRATION_LITE = 1501,
    OEMINFO_PWRUPWP_OIS_GYROGAIN_LITE = 1502,
    OEMINFO_PWRUPWP_ACCEL_SENSOR_DATA_LITE = 1503,
    OEMINFO_PWRUPWP_CAP_PROX_DATA_INFO_LITE = 1504,
    OEMINFO_PWRUPWP_SENSOR_LIGHT_BH1745_CALIBRATION_LITE = 1505,
    OEMINFO_PWRUPWP_GYRO_SENSOR_DATA_LITE = 1506,
    OEMINFO_PWRUPWP_QRCODE_BSN_LITE = 1507,
    OEMINFO_PWRUPWP_CAMERA_LASERCALIB_LITE = 1508,
    OEMINFO_PWRUPWP_MOD_HASH_LITE = 1509,
    OEMINFO_PWRUPWP_TOF_EYE_SAFE_TYPE_LITE = 1510,
    OEMINFO_PWRUPWP_LANMAC_LITE = 1511,
    OEMINFO_PWRUPWP_CASTHDCP_LITE = 1512,
    OEMINFO_PWRUPWP_MODSN_CHECK_LITE = 1513,
    OEMINFO_PWRUPWP_ALSENSOR_LITE = 1514,
    OEMINFO_PWRUPWP_ALS_UNDER_TP_CALIDATA_LITE = 1515,
    OEMINFO_ROOTWP_NAL_CODE_TYPE = 1534,
    /* the id from 2000 to 2050 of 8k area are reserved */
    /* the id from 2200 to 2210 of 64k area are reserved */
    OEMINFO_PWRUPWP_CAMERA_HDC_LITE = 2211,
    OEMINFO_PWRUPWP_GMP_LITE = 2212,
    OEMINFO_PWRUPWP_GMP_EXT_LITE = 2213,
    /* the next id is used for  oeminfo_lite logo area */
    OEMINFO_NONEWP_ASCEND_TYPE_LITE = 2251,
    OEMINFO_NONEWP_LOW_POWER_TYPE_LITE = 2252,
    OEMINFO_NONEWP_POWER_CHARGING_TYPE_LITE = 2253,
} OeminfoTypeLite;

struct OeminfoV6ToLite {
    oeminfo_type oeminfoV6IdIndex;
    OeminfoTypeLite oeminfoLiteIdIndex;
};

static struct OeminfoV6ToLite g_oeminfoLiteTable[] = {
    { /* ----------- */
        0,
        0
    }, { /* oeminfoid=1 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_1
    }, { /* oeminfoid=2 */
        0,
        0
    }, { /* oeminfoid=3 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_3
    }, { /* oeminfoid=4 */
        0,
        0
    }, { /* oeminfoid=5 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_5
    }, { /* oeminfoid=6 */
        0,
        0
    }, { /* oeminfoid=7 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_7
    }, { /* oeminfoid=8 */
        OEMINFO_AMSS_VER_TYPE,
        OEMINFO_NONEWP_AMSS_VER_TYPE_LITE
    }, { /* oeminfoid=9 */
        OEMINFO_OEMSBL_VER_TYPE,
        OEMINFO_NONEWP_OEMSBL_VER_TYPE_LITE
    }, { /* oeminfoid=10 */
        OEMINFO_BAT_BLIMSW,
        OEMINFO_NONEWP_BAT_BLIMSW
    }, { /* oeminfoid = 11 */
        OEMINFO_BAT_BBINFO,
        OEMINFO_NONEWP_BAT_BBINFO
    }, { /* oeminfoid=12 */
        OEMINFO_BAT_HWCOUL,
        OEMINFO_NONEWP_BAT_HWCOUL,
    }, { /* oeminfoid=13 */
        OEMINFO_PPR,
        OEMINFO_NONEWP_PPR
    }, { /* oeminfoid=14 */
        OEMINFO_UPDATE_TYPE,
        OEMINFO_NONEWP_UPDATE_TYPE_LITE
    }, { /* oeminfoid=15 */
        OEMINFO_BOARD_CODE_TYPE,
        OEMINFO_ROOTWP_BOARD_CODE_TYPE_LITE
    }, { /* oeminfoid=16 */
        OEMINFO_ALS_UNDER_TP_CALIDATA,
        OEMINFO_PWRUPWP_ALS_UNDER_TP_CALIDATA_LITE
    }, { /* oeminfoid=17 */
        0,
        0
    }, { /* oeminfoid=18 */
        OEMINFO_VENDER_AND_COUNTRY_NAME,
        OEMINFO_ROOTWP_VENDER_AND_COUNTRY_NAME_LITE
    }, { /* oeminfoid=19 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_19
    }, { /* oeminfoid=20 */
        OEMINFO_UTAPKAUTORUN,
        OEMINFO_NONEWP_UTAPKAUTORUN
    }, { /* oeminfoid=21 */
        OEMINFO_DDC_TYPE,
        OEMINFO_ROOTWP_DDC_TYPE_LITE
    }, { /* oeminfoid=22 */
        OEMINFO_POST_CUSTOM_TYPE,
        OEMINFO_NONEWP_POST_CUSTOM_TYPE_LITE
    }, { /* oeminfoid=23 */
        OEMINFO_WIFI_TEST,
        OEMINFO_NONEWP_WIFI_TEST_LITE
    }, { /* oeminfoid=24 */
        OEMINFO_IMEI2_NUM,
        OEMINFO_ROOTWP_IMEI2_NUM_LITE
    }, { /* oeminfoid=25 */
        OEMINFO_CUSTOMEI,
        OEMINFO_NONEWP_CUSTOMEI_LITE
    }, { /* oeminfoid=26 */
        OEMINFO_FACT_INFO,
        OEMINFO_ROOTWP_FACT_INFO_LITE
    }, { /* oeminfoid=27 */
        OEMINFO_FACT_ODM,
        OEMINFO_NONEWP_FACT_ODM_LITE
    }, { /* oeminfoid=28 */
        OEMINFO_HWSB_AES_PWD,
        OEMINFO_ROOTWP_HWSB_AES_PWD_LITE
    }, { /* oeminfoid=29 */
        OEMINFO_HWSB_LOCK_STATE,
        OEMINFO_NONEWP_HWSB_LOCK_STATE_LITE
    }, { /* oeminfoid=30 */
        OEMINFO_HWFB_LOCK_STATE,
        OEMINFO_NONEWP_HWFB_LOCK_STATE_LITE
    }, { /* oeminfoid=31 */
        OEMINFO_CASTHDCP,
        OEMINFO_PWRUPWP_CASTHDCP_LITE
    }, { /* oeminfoid=32 */
        OEMINFO_SENSOR_PROXIMITY_PA2240_CALIBRATION,
        OEMINFO_PWRUPWP_SENSOR_PROXIMITY_PA2240_CALIBRATION_LITE
    }, { /* oeminfoid=33 */
        OEMINFO_MODSN_CHECK,
        OEMINFO_PWRUPWP_MODSN_CHECK_LITE
    }, { /* oeminfoid=34 */
        OEMINFO_HOTA_BOOT_MODE,
        OEMINFO_NONEWP_HOTA_BOOT_MODE
    }, { /* oeminfoid=35 */
        0,
        0
    }, { /* oeminfoid=36 */
        0,
        0
    }, { /* oeminfoid=37 */
        OEMINFO_ALSENSOR,
        OEMINFO_PWRUPWP_ALSENSOR_LITE
    }, { /* oeminfoid=38 */
        OEMINFO_SKU_TYPE,
        OEMINFO_ROOTWP_SKU_TYPE_LITE
    }, { /* oeminfoid=39 */
        OEMINFO_MANUFACTURE_DATE_TYPE,
        OEMINFO_ROOTWP_MANUFACTURE_DATE_TYPE_LITE
    }, { /* oeminfoid=40 */
        OEMINFO_VSIM_WIFIPOLL_FLAG,
        OEMINFO_NONEWP_VSIM_WIFIPOLL_FLAG_LITE
    }, { /* oeminfoid=41 */
        OEMINFO_VSIM_DOWNLOAD_STATUS,
        OEMINFO_NONEWP_VSIM_DOWNLOAD_STATUS_LITE
    }, { /* oeminfoid=42 */
        OEMINFO_OIS_GYROGAIN,
        OEMINFO_PWRUPWP_OIS_GYROGAIN_LITE
    }, { /* oeminfoid=43 */
        OEMINFO_VSIM_WIFI_CONN_STATUS,
        OEMINFO_NONEWP_VSIM_WIFI_CONN_STATUS_LITE
    }, { /* oeminfoid=44 */
        OEMINFO_LGU_SPECIAL_SN,
        OEMINFO_ROOTWP_LGU_SPECIAL_SN_LITE
    }, { /* oeminfoid=45 */
        OEMINFO_USER_USAGE_ACTIVDATE_TYPE,
        OEMINFO_NONEWP_USER_USAGE_ACTIVDATE_TYPE_LITE
    }, { /* oeminfoid=46 */
        OEMINFO_UNBIND_FLAG,
        OEMINFO_NONEWP_UNBIND_FLAG_LITE
    }, { /* oeminfoid=47 */
        OEMINFO_USB_PID_INDEX,
        OEMINFO_NONEWP_USB_PID_INDEX_LITE
    }, { /* oeminfoid=48 */
        OEMINFO_IMEI_TYPE,
        OEMINFO_ROOTWP_IMEI_TYPE_LITE
    }, { /* oeminfoid=49 */
        OEMINFO_MEID_TYPE,
        OEMINFO_ROOTWP_MEID_TYPE_LITE
    }, { /* oeminfoid=50 */
        OEMINFO_ESN_TYPE,
        OEMINFO_ROOTWP_ESN_TYPE_LITE
    }, { /* oeminfoid=51 */
        OEMINFO_BT_TYPE,
        OEMINFO_ROOTWP_BT_TYPE_LITE
    }, { /* oeminfoid=52 */
        OEMINFO_WIFI_TYPE,
        OEMINFO_ROOTWP_WIFI_TYPE_LITE
    }, { /* oeminfoid=53 */
        OEMINFO_FACTORY_INFO_TYPE,
        OEMINFO_ROOTWP_FACTORY_INFO_TYPE_LITE
    }, { /* oeminfoid=54 */
        OEMINFO_RUNTESTB_TYPE,
        OEMINFO_NONEWP_RUNTESTB_TYPE_LITE
    }, { /* oeminfoid=55 */
        OEMINFO_POPUPUSEDCOUNT,
        OEMINFO_NONEWP_POPUPUSEDCOUNT_LITE
    }, { /* oeminfoid=56 */
        OEMINFO_MOTORCODE,
        OEMINFO_NONEWP_MOTORCODE_LITE
    }, { /* oeminfoid=57 */
        OEMINFO_USB_PID_CUSTOM_TYPE,
        OEMINFO_NONEWP_USB_PID_CUSTOM_TYPE_LITE
    }, { /* oeminfoid=58 */
        OEMINFO_LANMAC,
        OEMINFO_PWRUPWP_LANMAC_LITE
    }, { /* oeminfoid=59 */
        OEMINFO_TIME_ON_TYPE,
        OEMINFO_ROOTWP_TIME_ON_TYPE
    }, { /* oeminfoid=60 */
        OEMINFO_POS_HALL_CALIBRATION_DATA,
        OEMINFO_NONEWP_POS_HALL_CALIBRATION_DATA
    }, { /* oeminfoid=61 */
        OEMINFO_SCCAL_CUR,
        OEMINFO_NONEWP_SCCAL_CUR_LITE
    }, { /* oeminfoid=62 */
        OEMINFO_CUR_OFFSET,
        OEMINFO_NONEWP_CUR_OFFSET_LITE
    }, { /* oeminfoid=63 */
        0,
        0
    }, { /* oeminfoid=64 */
        OEMINFO_CCFLAG,
        OEMINFO_NONEWP_CCFLAG_LITE
    }, { /* oeminfoid=65 */
        OEMINFO_TPCOLOR_TYPE,
        OEMINFO_NONEWP_TPCOLOR_TYPE_LITE
    }, { /* oeminfoid=66 */
        OEMINFO_CRYPTFS_STATE,
        OEMINFO_NONEWP_CRYPTFS_STATE_LITE
    }, { /* oeminfoid=67 */
        OEMINFO_ROOT_INFO_TYPE,
        OEMINFO_NONEWP_ROOT_INFO_TYPE_LITE
    }, { /* oeminfoid=68 */
        OEMINFO_RESCUEINFO_TYPE,
        OEMINFO_NONEWP_RESCUEINFO_TYPE_LITE
    }, { /* oeminfoid=69 */
        OEMINFO_TOF_REPAIR_EYE_SAFE_TYPE,
        OEMINFO_ROOTWP_TOF_EYE_SAFE_TYPE_LITE
    }, { /* oeminfoid=70 */
        OEMINFO_ACCEL_SENSOR_DATA,
        OEMINFO_PWRUPWP_ACCEL_SENSOR_DATA_LITE
    }, { /* oeminfoid=71 */
        OEMINFO_AUTH_ELABEL,
        OEMINFO_ROOTWP_AUTH_ELABEL_LITE
    }, { /* oeminfoid=72 */
        OEMINFO_DEBUG_EFUSE_FLAG,
        OEMINFO_NONEWP_DEBUG_EFUSE_FLAG_LITE
    }, { /* oeminfoid=73 */
        OEMINFO_WIFI_COUNTRY_CODE,
        OEMINFO_NONEWP_WIFI_COUNTRY_CODE_LITE
    }, { /* oeminfoid=74 */
        OEMINFO_CUST_OVMODE_STATE,
        OEMINFO_NONEWP_CUST_OVMODE_STATE_LITE
    }, { /* oeminfoid=75 */
        OEMINFO_PRELOAD_OVMODE_STATE,
        OEMINFO_NONEWP_PRELOAD_OVMODE_STATE_LITE
    }, { /* oeminfoid=76 */
        OEMINFO_SYSDLL_INSTALL_TYPE,
        OEMINFO_ROOTWP_SYSDLL_INSTALL_TYPE_LITE
    }, { /* oeminfoid=77 */
        OEMINFO_RETAIL_APK,
        OEMINFO_NONEWP_RETAIL_APK_LITE
    }, { /* oeminfoid=78 */
        OEMINFO_BUILD_NUMBER_TYPE,
        OEMINFO_ROOTWP_BUILD_NUMBER_TYPE_LITE
    }, { /* oeminfoid=79 */
        OEMINFO_CAEMRA_DF_TYPE,
        OEMINFO_NONEWP_CAEMRA_DF_TYPE_LITE
    }, { /* oeminfoid=80 */
        OEM_CAP_PROX_DATA_INFO,
        OEMINFO_PWRUPWP_CAP_PROX_DATA_INFO_LITE
    }, { /* oeminfoid=81 */
        OEMINFO_SINGLE_SIM,
        OEMINFO_ROOTWP_SINGLE_SIM_LITE
    }, { /* oeminfoid=82 */
        OEMINFO_CAMERA_HALL_OVERTURN_DATA,
        OEMINFO_NONEWP_CAMERA_HALL_OVERTURN_DATA_LITE
    }, { /* oeminfoid=83 */
        OEMINFO_AT_LOCK_PASSWORD_SHA256,
        OEMINFO_NONEWP_AT_LOCK_PASSWORD_SHA256_LITE
    }, { /* oeminfoid=84 */
        OEMINFO_RESET_ENTER_INFO,
        OEMINFO_NONEWP_RESET_ENTER_INFO_LITE
    }, { /* oeminfoid=85 */
        OEMINFO_UPDATE_ENTER_INFO,
        OEMINFO_NONEWP_UPDATE_ENTER_INFO_LITE
    }, { /* oeminfoid=86 */
        OEMINFO_DAP_TIME,
        OEMINFO_NONEWP_DAP_TIME_LITE
    }, { /* oeminfoid=87 */
        OEMINFO_PSID_DATA,
        OEMINFO_NONEWP_PSID_DATA_LITE
    }, { /* oeminfoid=88 */
        OEMINFO_RESOURCE_VERSION,
        OEMINFO_NONEWP_RESOURCE_VERSION_LITE
    }, { /* oeminfoid=89 */
        OEMINFO_CRYPTFS_DATA,
        OEMINFO_NONEWP_CRYPTFS_DATA_LITE
    }, { /* oeminfoid=90 */
        0,
        0
    }, { /* oeminfoid=91 */
        OEMINFO_PRODUCT_MODEL_TYPE,
        OEMINFO_ROOTWP_PRODUCT_MODEL_TYPE_LITE
    }, { /* oeminfoid=92 */
        OEMINFO_INITRC_TRACER,
        OEMINFO_NONEWP_INITRC_TRACER_LITE
    }, { /* oeminfoid=93 */
        OEMINFO_FBLOCK_STAT_INFO,
        OEMINFO_NONEWP_FBLOCK_STAT_INFO_LITE
    }, { /* oeminfoid=94 */
        OEMINFO_VENDER_AND_COUNTRY_NAME_COTA,
        OEMINFO_NONEWP_VENDER_AND_COUNTRY_NAME_COTA_LITE
    }, { /* oeminfoid=95 */
        OEMINFO_ANTITHIVES_STATE,
        OEMINFO_NONEWP_ANTITHIVES_STATE_LITE
    }, { /* oeminfoid=96 */
        OEMINFO_WIFI_CAL_INDEX,
        OEMINFO_NONEWP_WIFI_CAL_INDEX_LITE
    }, { /* oeminfoid=97 */
        OEMINFO_DEVICE_MODEL,
        OEMINFO_ROOTWP_DEVICE_MODEL_LITE
    }, { /* oeminfoid=98 */
        OEMINFO_FRP_OPEN_FLAG,
        OEMINFO_ROOTWP_FRP_OPEN_FLAG_LITE
    }, { /* oeminfoid=99 */
        OEMINFO_FRP_KEY,
        OEMINFO_ROOTWP_FRP_KEY_LITE
    }, { /* oeminfoid=100 */
        OEMINFO_SD_LOCK_PASSWD,
        OEMINFO_NONEWP_SD_LOCK_PASSWD_LITE
    }, { /* oeminfoid=101 */
        OEMINFO_MAIN_VERSION,
        OEMINFO_NONEWP_MAIN_VERSION_LITE
    }, { /* oeminfoid=102 */
        OEMINFO_TOF_EYE_SAFE_TYPE,
        OEMINFO_PWRUPWP_TOF_EYE_SAFE_TYPE_LITE
    }, { /* oeminfoid=103 */
        OEMINFO_FB_STP_TYPE,
        OEMINFO_NONEWP_FB_STP_TYPE_LITE
    }, { /* oeminfoid=104 */
        OEMINFO_BOOTANIM_SWITCH,
        OEMINFO_NONEWP_BOOTANIM_SWITCH_LITE
    }, { /* oeminfoid=105 */
        OEMINFO_BOOTANIM_SHUTFLAG,
        OEMINFO_NONEWP_BOOTANIM_SHUTFLAG_LITE
    }, { /* oeminfoid=106 */
        OEMINFO_BOOTANIM_RINGMODE,
        OEMINFO_NONEWP_BOOTANIM_RINGMODE_LITE
    }, { /* oeminfoid=107 */
        OEMINFO_BOOTANIM_RINGDEX,
        OEMINFO_NONEWP_BOOTANIM_RINGDEX_LITE
    }, { /* oeminfoid=108 */
        OEMINFO_DATA_PART_FAULT_TIMES,
        OEMINFO_NONEWP_DATA_PART_FAULT_TIMES_LITE
    }, { /* oeminfoid=109 */
        OEMINFO_CLOUD_ROM_INSTALL_STAT,
        OEMINFO_NONEWP_CLOUD_ROM_INSTALL_STAT_LITE
    }, { /* oeminfoid=110 */
        OEMINFO_APPS_NO_INSTALL_TYPE,
        OEMINFO_NONEWP_APPS_NO_INSTALL_TYPE_LITE
    }, { /* oeminfoid=111 */
        OEMINFO_SYSTEM_VERSION,
        OEMINFO_NONEWP_SYSTEM_VERSION_LITE
    }, { /* oeminfoid=112 */
        OEMINFO_DEV_NG_INFO,
        OEMINFO_NONEWP_DEV_NG_INFO_LITE
    }, { /* oeminfoid=113 */
        OEMINFO_CAMERA_SPECS,
        OEMINFO_NONEWP_CAMERA_SPECS_LITE
    }, { /* oeminfoid=114 */
        OEMINFO_GAMMA_DATA,
        OEMINFO_NONEWP_GAMMA_DATA_LITE
    }, { /* oeminfoid=115 */
        OEMINFO_GAMMA_LEN,
        OEMINFO_NONEWP_GAMMA_LEN_LITE
    }, { /* oeminfoid=116 */
        OEMINFO_SENSOR_LIGHT_BH1745_CALIBRATION,
        OEMINFO_PWRUPWP_SENSOR_LIGHT_BH1745_CALIBRATION_LITE
    }, { /* oeminfoid=117 */
        OEMINFO_MCC_MNC_TYPE,
        OEMINFO_NONEWP_MCC_MNC_TYPE_LITE
    }, { /* oeminfoid=118 */
        OEMINFO_PRODUCE_PHASE_FLAG,
        OEMINFO_ROOTWP_PRODUCE_PHASE_FLAG_LITE
    }, { /* oeminfoid=119 */
        OEMINFO_GYRO_SENSOR_DATA,
        OEMINFO_PWRUPWP_GYRO_SENSOR_DATA_LITE
    }, { /* oeminfoid=120 */
        OEMINFO_OPERATOR_INFO,
        OEMINFO_NONEWP_OPERATOR_INFO_LITE
    }, { /* oeminfoid=121 */
        OEMINFO_HOTA_UPDATE_AUTH_LOCK,
        OEMINFO_NONEWP_HOTA_UPDATE_AUTH_LOCK_LITE
    }, { /* oeminfoid=122 */
        OEMINFO_FACTORY_PRODUCT_VERSION_TYPE,
        OEMINFO_NONEWP_FACTORY_PRODUCT_VERSION_TYPE_LITE
    }, { /* oeminfoid=123 */
        OEMINFO_AUDIO_SMARTPA_CALIBRATION,
        OEMINFO_NONEWP_AUDIO_SMARTPA_CALIBRATION_LITE
    }, { /* oeminfoid=124 */
        OEMINFO_WIFIONLY_IDENTITY,
        OEMINFO_NONEWP_WIFIONLY_IDENTITY_LITE
    }, { /* oeminfoid=125 */
        OEMINFO_MMIAUTORUN,
        OEMINFO_ROOTWP_MMIAUTORUN_LITE
    }, { /* oeminfoid=126 */
        OEMINFO_LCD_BRIGHT_COLOR_CALIBRATION,
        OEMINFO_NONEWP_LCD_BRIGHT_COLOR_CALIBRATION_LITE
    }, { /* oeminfoid=127 */
        OEMINFO_FOTA_MODE,
        OEMINFO_NONEWP_FOTA_MODE_LITE
    }, { /* oeminfoid=128 */
        OEMINFO_MMIAUTOCFG,
        OEMINFO_ROOTWP_MMIAUTOCFG_LITE
    }, { /* oeminfoid=129 */
        OEMINFO_MARKETING_NAME,
        OEMINFO_NONEWP_MARKETING_NAME_LITE
    }, { /* oeminfoid=130 */
        OEMINFO_RD_LOCK_STATE,
        OEMINFO_ROOTWP_RD_LOCK_STATE_LITE
    }, { /* oeminfoid=131 */
        OEMINFO_ACCESS_LOCK_STATE,
        OEMINFO_ROOTWP_ACCESS_LOCK_STATE_LITE
    }, { /* oeminfoid=132 */
        OEMINFO_ACCESS_KEY,
        OEMINFO_ROOTWP_ACCESS_KEY_LITE
    }, { /* oeminfoid=133 */
        OEMINFO_OVMODE_STATE,
        OEMINFO_NONEWP_OVMODE_STATE_LITE
    }, { /* oeminfoid=134 */
        OEMINFO_ESIM_EID,
        OEMINFO_NONEWP_ESIM_EID_LITE
    }, { /* oeminfoid=135 */
        OEMINFO_OMADM_INFO,
        OEMINFO_NONEWP_OMADM_INFO_LITE
    }, { /* oeminfoid=136 */
        OEMINFO_ACTIVATION_STATUS_ID,
        OEMINFO_NONEWP_ACTIVATION_STATUS_ID_LITE
    }, { /* oeminfoid=137 */
        OEMINFO_HWPARENTCONTROL_RECOVER_DATA,
        OEMINFO_NONEWP_HWPARENTCONTROL_RECOVER_DATA_LITE
    }, { /* oeminfoid=138 */
        OEMINFO_CONTROL_FLAG,
        OEMINFO_ROOTWP_CONTROL_FLAG_LITE
    }, { /* oeminfoid=139 */
        OEMINFO_FIX_HOTA_INFO_INTI,
        OEMINFO_NONEWP_FIX_HOTA_INFO_INTI_LITE
    }, { /* oeminfoid=140 */
        OEMINFO_FIX_HOTA_INFO,
        OEMINFO_NONEWP_FIX_HOTA_INFO_LITE
    }, { /* oeminfoid=141 */
        OEMINFO_FIX_HOTA_STRING_INTI,
        OEMINFO_NONEWP_FIX_HOTA_STRING_INTI_LITE
    }, { /* oeminfoid=142 */
        OEMINFO_FIX_HOTA_STRING,
        OEMINFO_NONEWP_FIX_HOTA_STRING_LITE
    }, { /* oeminfoid=143 */
        OEMINFO_QRCODE_INFO,
        OEMINFO_ROOTWP_QRCODE_INFO_LITE
    }, { /* oeminfoid=144 */
        OEMINFO_QRCODE_BSN,
        OEMINFO_PWRUPWP_QRCODE_BSN_LITE
    }, { /* oeminfoid=145 */
        OEMINFO_VENDER_AND_COUNTRY_NAME_COTA_FACTORY,
        OEMINFO_NONEWP_VENDER_AND_COUNTRY_NAME_COTA_FACTORY_LITE
    }, { /* oeminfoid=146 */
        OEMINFO_USER_HOTA_UPDATE,
        OEMINFO_NONEWP_USER_HOTA_UPDATE_LITE
    }, { /* oeminfoid=147 */
        OEMINFO_LOG_SWITCH_TYPE,
        OEMINFO_ROOTWP_LOG_SWITCH_TYPE_LITE
    }, { /* oeminfoid=148 */
        OEMINFO_USE_DECRESS_BAT_VOL_FLAG,
        OEMINFO_NONEWP_USE_DECRESS_BAT_VOL_FLAG_LITE
    }, { /* oeminfoid=149 */
        OEMINFO_CAMERA_LASERCALIB,
        OEMINFO_PWRUPWP_CAMERA_LASERCALIB_LITE
    }, { /* oeminfoid=150 */
        OEMINFO_UPDATE_UDID,
        OEMINFO_NONEWP_UPDATE_UDID_LITE
    }, { /* oeminfoid=151 */
        OEMINFO_BASEBAND_VERSION_TYPE,
        OEMINFO_ROOTWP_BASEBAND_VERSION_TYPE_LITE
    }, { /* oeminfoid=152 */
        OEMINFO_FACTORY_SW_VERSION,
        OEMINFO_NONEWP_FACTORY_SW_VERSION_LITE
    }, { /* oeminfoid=153 */
        OEMINFO_PRELOAD_APP_BATCH,
        OEMINFO_NONEWP_PRELOAD_APP_BATCH_LITE
    }, { /* oeminfoid=154 */
        OEMINFO_CUST_Y_CABLE_TYPE,
        OEMINFO_NONEWP_CUST_Y_CABLE_TYPE_LITE
    }, { /* oeminfoid=155 */
        OEMINFO_UDID_CODE_TYPE,
        OEMINFO_ROOTWP_UDID_CODE_TYPE_LITE
    }, { /* oeminfoid=156 */
        OEMINFO_BASE_VER_TYPE,
        OEMINFO_NONEWP_BASE_VER_TYPE_LITE
    }, { /* oeminfoid=157 */
        OEMINFO_CUST_VER_TYPE,
        OEMINFO_NONEWP_CUST_VER_TYPE_LITE
    }, { /* oeminfoid=158 */
        OEMINFO_PRELOAD_VER_TYPE,
        OEMINFO_NONEWP_PRELOAD_VER_TYPE_LITE
    }, { /* oeminfoid=159 */
        0,
        0
    }, { /* oeminfoid=160 */
        0,
        0
    }, { /* oeminfoid=161 */
        OEMINFO_SDUPDATE_TYPE,
        OEMINFO_NONEWP_SDUPDATE_TYPE_LITE
    }, { /* oeminfoid=162 */
        OEMINFO_NAL_CODE_TYPE,
        OEMINFO_ROOTWP_NAL_CODE_TYPE
    }, { /* oeminfoid=163 */
        OEMINFO_ENABLE_RETREAD,
        OEMINFO_NONEWP_ENABLE_RETREAD_LITE
    }, { /* oeminfoid=164 */
        OEMINFO_BDRT_TYPE,
        OEMINFO_NONEWP_BDRT_TYPE_LITE
    }, { /* oeminfoid=165 */
        OEMINFO_MOD_HASH,
        OEMINFO_PWRUPWP_MOD_HASH_LITE
    }, { /* oeminfoid=166 */
        OEMINFO_SYSTEM_UPDATE_AUTH_TOKEN_INFO,
        OEMINFO_NONEWP_SYSTEM_UPDATE_AUTH_TOKEN_INFO_LITE
    }, { /* oeminfoid=167 */
        OEMINFO_ENCRYPT_INFO,
        OEMINFO_NONEWP_ENCRYPT_INFO_LITE
    }, { /* oeminfoid=168 */
        OEMINFO_CONTROL_BIT,
        OEMINFO_ROOTWP_CONTROL_BIT_LITE
    }, { /* oeminfoid=169 */
        OEMINFO_MALWARE_DIAGNOSE,
        OEMINFO_NONEWP_MALWARE_DIAGNOSE_LITE
    }, { /* oeminfoid=170 */
        OEMINFO_RETREAD_DIAGNOSE,
        OEMINFO_NONEWP_RETREAD_DIAGNOSE_LITE
    }, { /* oeminfoid=171 */
        OEMINFO_ROOT_DIAGNOSE,
        OEMINFO_NONEWP_ROOT_DIAGNOSE_LITE
    }, { /* oeminfoid=172 */
        OEMINFO_SYSTEM_VERSION_B,
        OEMINFO_NONEWP_SYSTEM_VERSION_B_LITE
    }, { /* oeminfoid=173 */
        OEMINFO_ANDROID_VERSION,
        OEMINFO_NONEWP_ANDROID_VERSION_LITE
    }, { /* oeminfoid=174 */
        OEMINFO_ANDROID_VERSION_B,
        OEMINFO_NONEWP_ANDROID_VERSION_B_LITE
    }, { /* oeminfoid=175 */
        OEMINFO_SLOT_INFO_A,
        OEMINFO_NONEWP_SLOT_INFO_A_LITE
    }, { /* oeminfoid=176 */
        OEMINFO_SLOT_INFO_B,
        OEMINFO_NONEWP_SLOT_INFO_B_LITE
    }, { /* oeminfoid=177 */
        OEMINFO_SLOT_STATUS,
        OEMINFO_NONEWP_SLOT_STATUS_LITE
    }, { /* oeminfoid=178 */
        OEMINFO_VERITY_MODE_UPDATE_STATUS,
        OEMINFO_NONEWP_VERITY_MODE_UPDATE_STATUS_LITE
    }, { /* oeminfoid=179 */
        OEMINFO_SYSTEM_UPDATE_STATE,
        OEMINFO_NONEWP_SYSTEM_UPDATE_STATE_LITE
    }, { /* oeminfoid=180 */
        OEMINFO_CUSTOM_VERSION,
        OEMINFO_NONEWP_CUSTOM_VERSION_LITE
    }, { /* oeminfoid=181 */
        OEMINFO_CUSTOM_VERSION_B,
        OEMINFO_NONEWP_CUSTOM_VERSION_B_LITE
    }, { /* oeminfoid=182 */
        OEMINFO_PRELOAD_VERSION,
        OEMINFO_NONEWP_PRELOAD_VERSION_LITE
    }, { /* oeminfoid=183 */
        OEMINFO_PRELOAD_VERSION_B,
        OEMINFO_NONEWP_PRELOAD_VERSION_B_LITE
    }, { /* oeminfoid=184 */
        OEMINFO_GROUP_VERSION,
        OEMINFO_NONEWP_GROUP_VERSION_LITE
    }, { /* oeminfoid=185 */
        OEMINFO_GROUP_VERSION_B,
        OEMINFO_NONEWP_GROUP_VERSION_B_LITE
    }, { /* oeminfoid=186 */
        OEMINFO_BASE_VERSION,
        OEMINFO_NONEWP_BASE_VERSION_LITE
    }, { /* oeminfoid=187 */
        OEMINFO_BASE_VERSION_B,
        OEMINFO_NONEWP_BASE_VERSION_B_LITE
    }, { /* oeminfoid=188 */
        OEMINFO_COTA_REBOOT_UPDATE_PATH,
        OEMINFO_NONEWP_COTA_REBOOT_UPDATE_PATH_LITE
    }, { /* oeminfoid=189 */
        OEMINFO_CUSTOM_C_VERSION,
        OEMINFO_NONEWP_CUSTOM_C_VERSION_LITE
    }, { /* oeminfoid=190 */
        OEMINFO_RUNTEST_TYPE,
        OEMINFO_NONEWP_RUNTEST_TYPE_LITE
    }, { /* oeminfoid=191 */
        OEMINFO_MMITEST_TYPE,
        OEMINFO_NONEWP_MMITEST_TYPE_LITE
    }, { /* oeminfoid=192 */
        OEMINFO_OTA_SIMLOCK_ACTIVATED,
        OEMINFO_NONEWP_OTA_SIMLOCK_ACTIVATED_LITE
    }, { /* oeminfoid=193 */
        OEMINFO_ATLOCK_TYPE,
        OEMINFO_NONEWP_ATLOCK_TYPE_LITE
    }, { /* oeminfoid=194 */
        OEMINFO_RUNTEST2_TYPE,
        OEMINFO_NONEWP_RUNTEST2_TYPE_LITE
    }, { /* oeminfoid=195 */
        OEMINFO_RUNTIME_TYPE,
        OEMINFO_NONEWP_RUNTIME_TYPE_LITE
    }, { /* oeminfoid=196 */
        OEMINFO_MDATE_TYPE,
        OEMINFO_NONEWP_MDATE_TYPE_LITE
    }, { /* oeminfoid=197 */
        OEMINFO_MANUFACTURE_RESET_FLAG,
        OEMINFO_NONEWP_MANUFACTURE_RESET_FLAG_LITE
    }, { /* oeminfoid=198 */
        0,
        0
    }, { /* oeminfoid=199 */
        OEMINFO_BACKCOLOR,
        OEMINFO_NONEWP_BACKCOLOR_LITE
    }, { /* oeminfoid=200 */
        0,
        0
    }, { /* oeminfoid=201 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_201
    }, { /* oeminfoid=202 */
        0,
        0
    }, { /* oeminfoid=203 */
        OEMINFO_REUSED_ID_203_8K_VALID_SIZE_448_BYTE,
        OEMINFO_NONEWP_REUSED_ID_551_8K_VALID_SIZE_448_BYTE_LITE
    }, { /* oeminfoid=204 */
        OEMINFO_REUSED_ID_204_8K_VALID_SIZE_64_BYTE,
        OEMINFO_NONEWP_REUSED_ID_552_8K_VALID_SIZE_64_BYTE_LITE
    }, { /* oeminfoid=205 */
        OEMINFO_FMD_VERIFY_DATA,
        OEMINFO_NONEWP_FMD_VERIFY_DATA_LITE
    }, { /* oeminfoid=206 */
        OEMINFO_DEVICE_CERTIFICATE1,
        OEMINFO_ROOTWP_DEVICE_CERTIFICATE1_LITE
    }, { /* oeminfoid=207 */
        OEMINFO_DEVICE_CERTIFICATE2,
        OEMINFO_ROOTWP_DEVICE_CERTIFICATE2_LITE
    }, { /* oeminfoid=208 */
        OEMINFO_KEY_ATTESTATION,
        OEMINFO_ROOTWP_KEY_ATTESTATION_LITE
    }, { /* oeminfoid=209 */
        OEMINFO_FCDEG,
        OEMINFO_NONEWP_FCDEG_LITE
    }, { /* oeminfoid=210 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_210
    }, { /* oeminfoid=211 */
        0,
        0
    }, { /* oeminfoid=212 */
        0,
        0
    }, { /* oeminfoid=213 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_213
    }, { /* oeminfoid=214 */
        0,
        0
    }, { /* oeminfoid=215 */
        0,
        0
    }, { /* oeminfoid=216 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_216
    }, { /* oeminfoid=217 */
        0,
        0
    }, { /* oeminfoid=218 */
        0,
        0
    }, { /* oeminfoid=219 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_219
    }, { /* oeminfoid=220 */
        0,
        0
    }, { /* oeminfoid=221 */
        0,
        0
    }, { /* oeminfoid=222 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_222
    }, { /* oeminfoid=223 */
        0,
        0
    }, { /* oeminfoid=224 */
        0,
        0
    }, { /* oeminfoid=225 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_225
    }, { /* oeminfoid=226 */
        0,
        0
    }, { /* oeminfoid=227 */
        0,
        0
    }, { /* oeminfoid=228 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_228
    }, { /* oeminfoid=229 */
        0,
        0
    }, { /* oeminfoid=230 */
        0,
        0
    }, { /* oeminfoid=231 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_231
    }, { /* oeminfoid=232 */
        0,
        0
    }, { /* oeminfoid=233 */
        0,
        0
    }, { /* oeminfoid=234 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_234
    }, { /* oeminfoid=235 */
        0,
        0
    }, { /* oeminfoid=236 */
        0,
        0
    }, { /* oeminfoid=237 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_237
    }, { /* oeminfoid=238 */
        0,
        0
    }, { /* oeminfoid=239 */
        0,
        0
    }, { /* oeminfoid=240 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_240
    }, { /* oeminfoid=241 */
        0,
        0
    }, { /* oeminfoid=242 */
        0,
        0
    }, { /* oeminfoid=243 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_243
    }, { /* oeminfoid=244 */
        0,
        0
    }, { /* oeminfoid=245 */
        0,
        0
    }, { /* oeminfoid=246 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_246
    }, { /* oeminfoid=247 */
        0,
        0,
    }, { /* oeminfoid=248 */
        0,
        0
    }, { /* oeminfoid=249 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_249
    }, { /* oeminfoid=250 */
        0,
        0
    }, { /* oeminfoid=251 */
        0,
        0
    }, { /* oeminfoid=252 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_252
    }, { /* oeminfoid=253 */
        0,
        0
    }, { /* oeminfoid=254 */
        0,
        0
    }, { /* oeminfoid=255 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_255
    }, { /* oeminfoid=256 */
        0,
        0
    }, { /* oeminfoid=257 */
        0,
        0
    }, { /* oeminfoid=258 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_258
    }, { /* oeminfoid=259 */
        0,
        0
    }, { /* oeminfoid=260 */
        0,
        0
    }, { /* oeminfoid=261 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_261
    }, { /* oeminfoid=262 */
        0,
        0
    }, { /* oeminfoid=263 */
        0,
        0
    }, { /* oeminfoid=264 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_264
    }, { /* oeminfoid=265 */
        0,
        0
    }, { /* oeminfoid=266 */
        0,
        0
    }, { /* oeminfoid=267 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_267
    }, { /* oeminfoid=268 */
        0,
        0
    }, { /* oeminfoid=269 */
        0,
        0
    }, { /* oeminfoid=270 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_270
    }, { /* oeminfoid=271 */
        0,
        0
    }, { /* oeminfoid=272 */
        0,
        0
    }, { /* oeminfoid=273 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_273
    }, { /* oeminfoid=274 */
        0,
        0
    }, { /* oeminfoid=275 */
        0,
        0
    }, { /* oeminfoid=276 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_276
    }, { /* oeminfoid=277 */
        0,
        0
    }, { /* oeminfoid=278 */
        0,
        0
    }, { /* oeminfoid=279 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_279
    }, { /* oeminfoid=280 */
        0,
        0
    }, { /* oeminfoid=281 */
        0,
        0
    }, { /* oeminfoid=282 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_282
    }, { /* oeminfoid=283 */
        0,
        0
    }, { /* oeminfoid=284 */
        0,
        0
    }, { /* oeminfoid=285 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_285
    }, { /* oeminfoid=286 */
        0,
        0
    }, { /* oeminfoid=287 */
        0,
        0
    }, { /* oeminfoid=288 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_288
    }, { /* oeminfoid=289 */
        0,
        0
    }, { /* oeminfoid=290 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_290
    }, { /* oeminfoid=291 */
        0,
        0
    }, { /* oeminfoid=292 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_292
    }, { /* oeminfoid=293 */
        0,
        0
    }, { /* oeminfoid=294 */
        0,
        0
    }, { /* oeminfoid=295 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_295
    }, { /* oeminfoid=296 */
        0,
        0
    }, { /* oeminfoid=297 */
        0,
        0
    }, { /* oeminfoid=298 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_298
    }, { /* oeminfoid=299 */
        0,
        0
    }, { /* oeminfoid=300 */
        0,
        0
    }, { /* oeminfoid=301 */
        OEMINFO_CAMERA_TOF_CALIBRATION1_TYPE,
        OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION1_TYPE_LITE
    }, { /* oeminfoid=302 */
        OEMINFO_CAMERA_TOF_CALIBRATION2_TYPE,
        OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION2_TYPE_LITE
    }, { /* oeminfoid=303 */
        OEMINFO_FASTBOOT_FMD_DATA,
        OEMINFO_NONEWP_FASTBOOT_FMD_DATA_LITE
    }, { /* oeminfoid=304 */
        OEMINFO_BASE_CLOUD_ROM_LIST,
        OEMINFO_NONEWP_BASE_CLOUD_ROM_LIST_LITE
    }, { /* oeminfoid=305 */
        OEMINFO_CAMERA_TOF_CALIBRATION3_TYPE,
        OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION3_TYPE_LITE
    }, { /* oeminfoid=306 */
        OEMINFO_CAMERA_TOF_CALIBRATION4_TYPE,
        OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION4_TYPE_LITE
    }, { /* oeminfoid=307 */
        OEMINFO_CAMERA_TOF_CALIBRATION5_TYPE,
        OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION4_TYPE_LITE
    }, { /* oeminfoid=308 */
        OEMINFO_CAMERA_TOF_CALIBRATION6_TYPE,
        OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION4_TYPE_LITE
    }, { /* oeminfoid=309 */
        OEMINFO_CAMERA_TOF_CALIBRATION7_TYPE,
        OEMINFO_NONEWP_CAMERA_TOF_CALIBRATION4_TYPE_LITE
    }, { /* oeminfoid=310 */
        OEMINFO_CAMERA_BLC_CALIB,
        OEMINFO_NONEWP_CAMERA_BLC_CALIB_LITE
    }, { /* oeminfoid=311 */
        OEMINFO_GMP,
        OEMINFO_PWRUPWP_GMP_LITE
    }, { /* oeminfoid=312 */
        OEMINFO_SCREEN_DATA,
        OEMINFO_ROOTWP_SCREEN_DATA_LITE
    }, { /* oeminfoid=313 */
        OEMINFO_CGM_SCG_DATA,
        OEMINFO_NONEWP_CGM_SCG_DATA_LITE
    }, { /* oeminfoid=314 */
        OEMINFO_CGM_WCG_DATA,
        OEMINFO_NONEWP_CGM_WCG_DATA_LITE
    }, { /* oeminfoid=315 */
        OEMINFO_GMP_EXT,
        OEMINFO_PWRUPWP_GMP_EXT_LITE,
    }, { /* oeminfoid=316 */
        OEMINFO_CUST_LOGO_EXTERN,
        OEMINFO_ROOTWP_CUST_LOGO_EXTERN
    }, { /* oeminfoid=317 */
        OEMINFO_POWER_CHARGING_TYPE_EXTERN,
        OEMINFO_ROOTWP_POWER_CHARGING_TYPE_EXTERN
    }, { /* oeminfoid=318 */
        OEMINFO_LOW_POWER_TYPE_EXTERN,
        OEMINFO_ROOTWP_LOW_POWER_TYPE_EXTERN
    }, { /* oeminfoid=319 */
        OEMINFO_COLOR_SENSOR_CALI_MATRIX,
        OEMINFO_ROOTWP_COLOR_SENSOR_CALI_MATRIX
    }, { /* oeminfoid=320 */
        0,
        0
    }, { /* oeminfoid=321 */
        0,
        0
    }, { /* oeminfoid=322 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_322
    }, { /* oeminfoid=323 */
        0,
        0
    }, { /* oeminfoid=324 */
        OEMINFO_WCNSS_FIR_BAK_TYPE,
        OEMINFO_NONEWP_WCNSS_FIR_BAK_TYPE_LITE
    }, { /* oeminfoid=325 */
        OEMINFO_SPECCALIB0,
        OEMINFO_NONEWP_SPECCALIB0_LITE
    }, { /* oeminfoid=326 */
        OEMINFO_SPECCALIB1,
        OEMINFO_NONEWP_SPECCALIB1_LITE
    }, { /* oeminfoid=327 */
        0,
        0
    }, { /* oeminfoid=328 */
        0,
        0
    }, { /* oeminfoid=329 */
        OEMINFO_CAMERA_HDC,
        OEMINFO_PWRUPWP_CAMERA_HDC_LITE
    }, { /* oeminfoid=330 */
        OEMINFO_NFC_SEID,
        OEMINFO_ROOTWP_NFC_SEID_LITE
    }, { /* oeminfoid=331 */
        OEMINFO_CONTROL_MODE_DATA,
        OEMINFO_NONEWP_CONTROL_MODE_DATA
    }, { /* oeminfoid=332 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_332
    }, { /* oeminfoid=333 */
        0,
        0
    }, { /* oeminfoid=334 */
        0,
        0
    }, { /* oeminfoid=335 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_335
    }, { /* oeminfoid=336 */
        0,
        0
    }, { /* oeminfoid=337 */
        0,
        0
    }, { /* oeminfoid=338 */
        0,
        OEMINFO_UNUSEED_TYPE_USER_LITE_338
    }, { /* oeminfoid=339 */
        0,
        0
    }, { /* oeminfoid=340 */
        OEMINFO_CAMERA_EEPROM_DATA_00,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_00_LITE
    }, { /* oeminfoid=341 */
        OEMINFO_CAMERA_EEPROM_DATA_01,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_01_LITE
    }, { /* oeminfoid=342 */
        OEMINFO_CAMERA_EEPROM_DATA_02,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_02_LITE
    }, { /* oeminfoid=343 */
        OEMINFO_CAMERA_EEPROM_DATA_03,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_03_LITE
    }, { /* oeminfoid=344 */
        OEMINFO_CAMERA_EEPROM_DATA_04,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_04_LITE
    }, { /* oeminfoid=345 */
        OEMINFO_CAMERA_EEPROM_DATA_05,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_05_LITE
    }, { /* oeminfoid=346 */
        OEMINFO_CAMERA_EEPROM_DATA_06,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_06_LITE
    }, { /* oeminfoid=347 */
        OEMINFO_CAMERA_EEPROM_DATA_07,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_07_LITE
    }, { /* oeminfoid=348 */
        OEMINFO_CAMERA_EEPROM_DATA_08,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_08_LITE
    }, { /* oeminfoid=349 */
        OEMINFO_CAMERA_EEPROM_DATA_09,
        OEMINFO_NONEWP_CAMERA_EEPROM_DATA_09_LITE
    }, { /* oeminfoid=350 */
        0,
        0
    }, { /* oeminfoid=351 */
        OEMINFO_ASCEND_TYPE,
        OEMINFO_NONEWP_ASCEND_TYPE_LITE
    }, { /* oeminfoid=352 */
        OEMINFO_LOW_POWER_TYPE,
        OEMINFO_NONEWP_LOW_POWER_TYPE_LITE
    }, { /* oeminfoid=353 */
        OEMINFO_POWER_CHARGING_TYPE,
        OEMINFO_NONEWP_POWER_CHARGING_TYPE_LITE
    },
};

#endif /* INCLUDE_OEMINFO_V6_TO_LITE_H */
