#=============================================================================
#  add new config for devices check
#  add new config for factory cmdline parse
#  add new config for antenna board gpio match
#  add new config for audio match
#=============================================================================

obj-$(CONFIG_HUAWEI_KSTATE)               += hw_kstate/
obj-$(CONFIG_ANTENNA_BOARDID_GPIO_DETECT) += antenna_board_gpio_match/
obj-$(CONFIG_ANTENNA_BOARDID_ADC_MATCH)   += antenna_board_adc_match/
obj-$(CONFIG_HUAWEI_AUDIO)                += audio/
obj-$(CONFIG_HUAWEI_SENSORS)              += sensors/
obj-$(CONFIG_HUAWEI_SENSORS_2_0)          += sensor2_0/
obj-$(CONFIG_HUAWEI_SENSORS_AP)           += sensor_ap/
obj-$(CONFIG_PROC_IO_INFO)   += ioinfo/
obj-$(CONFIG_HUAWEI_SENSOR) += sensor/
obj-$(CONFIG_HUAWEI_CHARGER)              += power/
obj-y += hwpower/
obj-$(CONFIG_HUAWEI_MEMINFO_DUMP) += pmeminfo/
obj-$(CONFIG_RFFE_ANTENNA)                += antenna_cable/
obj-$(CONFIG_CARD_TRAY_GPIO_DETECT)                += card_tray/
obj-$(CONFIG_HUAWEI_VIRT_TO_PHYS)         += virt_to_phys/
obj-$(CONFIG_HUAWEI_DP)              += dp/
obj-$(CONFIG_HUAWEI_PD)              += usb/
obj-$(CONFIG_HWDPS) += hwdps/
obj-$(CONFIG_HUAWEI_VIBRATOR)        += vibrator/
obj-$(CONFIG_HW_COMB_KEY)            += comb_key/
obj-$(CONFIG_SCSI_UFS_ENHANCED_INLINE_CRYPTO) += scsi/ufs/
obj-$(CONFIG_MEM_INSPECT)                 += rmeminspect/
obj-$(CONFIG_HUAWEI_BASTET_MTK)   += net/
obj-$(CONFIG_HUAWEI_POPUP)   += popup/

