subdir-ccflags-y += -I$(srctree)/sound/soc/mediatek/common

ccflags-y += -Idrivers/huawei_platform/audio/cs35lxx -DCS35L36_GIT_VERSIONS=2.19
ccflags-y += -Idrivers/devkit/audiokit/
obj-$(CONFIG_CS35LXX) += cs35lxx.o
