ifeq ($(CONFIG_MTK_PLATFORM), "mt6873")
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6873/include
endif
ifeq ($(CONFIG_MTK_PLATFORM), "mt6853")
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6853/include
endif
obj-y += high_volt_vib.o