#
# FLP PDR configuration
#
ccflags-y  += -I$(srctree)/drivers/uni_drivers/contexthub/
ccflags-y  += -I$(srctree)/drivers/xhub_router/
#EXTRA_CFLAGS += -Idrivers/huawei/tzdriver

obj-$(CONFIG_HUAWEI_AR) += ar.o
