ccflags-y  += -I$(srctree)/drivers/xhub_router/

obj-$(CONFIG_CONTEXTHUB)   += common.o
obj-$(CONFIG_CONTEXTHUB)   += inputhub_api.o
obj-$(CONFIG_CONTEXTHUB)   += inputhub_wrapper.o
obj-$(CONFIG_HUAWEI_SOFTTIMER) += softtimer.o
obj-$(CONFIG_CONTEXTHUB)   += flp/
obj-$(CONFIG_CONTEXTHUB)   += ar/
