subdir-ccflags-y += -Werror -I$(srctree)/drivers/sensor_ap/pmic \
	-I$(srctree)/drivers/misc/mediatek/hwcam_hiview

obj-y += hw_pmic.o
obj-$(CONFIG_HUAWEI_PMIC_RT5112) += rt5112.o
obj-$(CONFIG_HUAWEI_PMIC_FAN53880) += fan53880.o

