subdir-ccflags-y += -Werror -I$(srctree)/drivers/power/supply/mediatek/charger
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc/
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
obj-$(CONFIG_RT9471_CHARGER) += rt9471_charger.o
