ccflags-y += -I$(srctree)/drivers/staging/android/ion
ccflags-y += -I$(srctree)/drivers/staging/android/ion/mtk
ccflags-y += -I$(srctree)/drivers/tzdriver
ccflags-y += -I$(srctree)/drivers/tzdriver/core
ccflags-y += -I$(srctree)/drivers/uni_drivers/secmem

obj-$(CONFIG_HW_VLTMM) += vltmm.o vltmm_agent.o
obj-$(CONFIG_HW_SECMEM) += secmem_tee_op.o sec_cma_alloc.o ion_sec_contig.o ion_seccg_heap.o
