obj-$(CONFIG_HKIP_MODULE_ALLOC) += hhee_module.o
obj-$(CONFIG_HUAWEI_HKIP)	+= hhee_log.o hhee_dev.o hhee_msg.o
obj-$(CONFIG_HUAWEI_HKIP)	+= service/
obj-$(CONFIG_HUAWEI_HKIP_DEBUG) += hhee_debugfs.o
obj-$(CONFIG_HUAWEI_HKIP_DEBUG) += hkip_test/
obj-y += mm/
