#
# Copyright (C) 2020-2023 huawei Software Operations
# Description: Kernel makfile file for the UFS
#
# Author: sizhiying
# Create: 2020-08-13
#
ccflags-y += -I$(srctree)/drivers/scsi/ufs
ccflags-y += -I$(srctree)/drivers/scsi/ufs/mediatek/mt6885
ccflags-y += -I$(srctree)/drivers/bootdevice
obj-$(CONFIG_SCSI_UFS_ENHANCED_INLINE_CRYPTO) += ufs-inline.o
