subdir-ccflags-y += -Werror -I$(srctree)/drivers/power/supply/mediatek/charger
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc/
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
obj-$(CONFIG_SGM41511H_CHARGER) += sgm41511h_charger.o