subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/inc
ccflags-y += -Idrivers/devkit/audiokit/
obj-$(CONFIG_HUAWEI_PD) += hw_pd.o
obj-$(CONFIG_TCPC_FUSB302) += fusb302b/
obj-$(CONFIG_TCPC_HI6526) += hi6526_pd/
