obj-$(CONFIG_USB_HW_F_ACM)      += usb_hw_f_acm.o
usb_hw_f_acm-y                  := hw_f_acm.o hw_u_serial.o
subdir-ccflags-y += -Werror -I$(srctree)/drivers/usb/gadget/function
obj-y      += hw_msconfig.o
