/*
 * Copyright (C) 2017 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 */

#include "kd_imgsensor.h"
#include "imgsensor_sensor_list.h"

/* Add Sensor Init function here
 * Note:
 * 1. Add by the resolution from ""large to small"", due to large sensor
 *    will be possible to be main sensor.
 *    This can avoid I2C error during searching sensor.
 * 2. This file should be the same as
 *    mediatek\custom\common\hal\imgsensor\src\sensorlist.cpp
 */
struct IMGSENSOR_SENSOR_LIST
	gimgsensor_sensor_list[MAX_NUM_OF_SUPPORT_SENSOR] = {
/*IMX*/
#if defined(IMX586_MIPI_RAW)
{IMX586_SENSOR_ID, SENSOR_DRVNAME_IMX586_MIPI_RAW, IMX586_MIPI_RAW_SensorInit},
#endif
#if defined(IMX319_MIPI_RAW)
{IMX319_SENSOR_ID, SENSOR_DRVNAME_IMX319_MIPI_RAW, IMX319_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3M5SX_MIPI_RAW)
{S5K3M5SX_SENSOR_ID, SENSOR_DRVNAME_S5K3M5SX_MIPI_RAW, S5K3M5SX_MIPI_RAW_SensorInit},
#endif
#if defined(GC02M0_MIPI_RAW)
{GC02M0_SENSOR_ID, SENSOR_DRVNAME_GC02M0_MIPI_RAW, GC02M0_MIPI_RAW_SensorInit},
#endif
#if defined(IMX519_MIPI_RAW)
{IMX519_SENSOR_ID, SENSOR_DRVNAME_IMX519_MIPI_RAW, IMX519_MIPI_RAW_SensorInit},
#endif
#if defined(IMX519DUAL_MIPI_RAW)
{IMX519_SENSOR_ID, SENSOR_DRVNAME_IMX519DUAL_MIPI_RAW,
	IMX519_MIPI_RAW_SensorInit},
#endif
#if defined(IMX499_MIPI_RAW)
{IMX499_SENSOR_ID, SENSOR_DRVNAME_IMX499_MIPI_RAW, IMX499_MIPI_RAW_SensorInit},
#endif
#if defined(IMX481_MIPI_RAW)
{IMX481_SENSOR_ID, SENSOR_DRVNAME_IMX481_MIPI_RAW, IMX481_MIPI_RAW_SensorInit},
#endif
#if defined(IMX576_MIPI_RAW)
{IMX576_SENSOR_ID, SENSOR_DRVNAME_IMX576_MIPI_RAW, IMX576_MIPI_RAW_SensorInit},
#endif
#if defined(IMX350_MIPI_RAW)
{IMX350_SENSOR_ID, SENSOR_DRVNAME_IMX350_MIPI_RAW, IMX350_MIPI_RAW_SensorInit},
#endif
#if defined(IMX398_MIPI_RAW)
{IMX398_SENSOR_ID, SENSOR_DRVNAME_IMX398_MIPI_RAW, IMX398_MIPI_RAW_SensorInit},
#endif
#if defined(IMX386_MIPI_RAW)
{IMX386_SENSOR_ID, SENSOR_DRVNAME_IMX386_MIPI_RAW, IMX386_MIPI_RAW_SensorInit},
#endif
#if defined(IMX386_MIPI_MONO)
{IMX386_MONO_SENSOR_ID, SENSOR_DRVNAME_IMX386_MIPI_MONO,
	IMX386_MIPI_MONO_SensorInit},
#endif
#if defined(IMX376_MIPI_RAW)
{IMX376_SENSOR_ID, SENSOR_DRVNAME_IMX376_MIPI_RAW, IMX376_MIPI_RAW_SensorInit},
#endif
#if defined(IMX362_MIPI_RAW)
{IMX362_SENSOR_ID, SENSOR_DRVNAME_IMX362_MIPI_RAW, IMX362_MIPI_RAW_SensorInit},
#endif
#if defined(IMX338_MIPI_RAW)
{IMX338_SENSOR_ID, SENSOR_DRVNAME_IMX338_MIPI_RAW, IMX338_MIPI_RAW_SensorInit},
#endif
#if defined(IMX318_MIPI_RAW)
{IMX318_SENSOR_ID, SENSOR_DRVNAME_IMX318_MIPI_RAW, IMX318_MIPI_RAW_SensorInit},
#endif
#if defined(IMX377_MIPI_RAW)
{IMX377_SENSOR_ID, SENSOR_DRVNAME_IMX377_MIPI_RAW, IMX377_MIPI_RAW_SensorInit},
#endif
#if defined(IMX230_MIPI_RAW)
{IMX230_SENSOR_ID, SENSOR_DRVNAME_IMX230_MIPI_RAW, IMX230_MIPI_RAW_SensorInit},
#endif
#if defined(IMX220_MIPI_RAW)
{IMX220_SENSOR_ID, SENSOR_DRVNAME_IMX220_MIPI_RAW, IMX220_MIPI_RAW_SensorInit},
#endif
#if defined(IMX219_MIPI_RAW)
{IMX219_SENSOR_ID, SENSOR_DRVNAME_IMX219_MIPI_RAW, IMX219_MIPI_RAW_SensorInit},
#endif
#if defined(IMX214_MIPI_RAW)
{IMX214_SENSOR_ID, SENSOR_DRVNAME_IMX214_MIPI_RAW, IMX214_MIPI_RAW_SensorInit},
#endif
#if defined(IMX214_MIPI_MONO)
{IMX214_MONO_SENSOR_ID, SENSOR_DRVNAME_IMX214_MIPI_MONO,
	IMX214_MIPI_MONO_SensorInit},
#endif
#if defined(IMX179_MIPI_RAW)
{IMX179_SENSOR_ID, SENSOR_DRVNAME_IMX179_MIPI_RAW, IMX179_MIPI_RAW_SensorInit},
#endif
#if defined(IMX178_MIPI_RAW)
{IMX178_SENSOR_ID, SENSOR_DRVNAME_IMX178_MIPI_RAW, IMX178_MIPI_RAW_SensorInit},
#endif
#if defined(IMX132_MIPI_RAW)
{IMX132MIPI_SENSOR_ID, SENSOR_DRVNAME_IMX132_MIPI_RAW,
	IMX132_MIPI_RAW_SensorInit},
#endif
#if defined(IMX135_MIPI_RAW)
{IMX135_SENSOR_ID, SENSOR_DRVNAME_IMX135_MIPI_RAW, IMX135_MIPI_RAW_SensorInit},
#endif
#if defined(IMX105_MIPI_RAW)
{IMX105_SENSOR_ID, SENSOR_DRVNAME_IMX105_MIPI_RAW, IMX105_MIPI_RAW_SensorInit},
#endif
#if defined(IMX073_MIPI_RAW)
{IMX073_SENSOR_ID, SENSOR_DRVNAME_IMX073_MIPI_RAW, IMX073_MIPI_RAW_SensorInit},
#endif
#if defined(IMX258_MIPI_RAW)
{IMX258_SENSOR_ID, SENSOR_DRVNAME_IMX258_MIPI_RAW, IMX258_MIPI_RAW_SensorInit},
#endif
#if defined(IMX258_MIPI_MONO)
{IMX258_MONO_SENSOR_ID, SENSOR_DRVNAME_IMX258_MIPI_MONO,
	IMX258_MIPI_MONO_SensorInit},
#endif
/*macro*/
/*OV (OmniVision)*/
#if defined(OV05A20_MIPI_RAW)
{OV05A20_SENSOR_ID, SENSOR_DRVNAME_OV05A20_MIPI_RAW,
	OV05A20_MIPI_RAW_SensorInit},
#endif
#if defined(OV02A10_SUNWIN)
{ OV02A10_SUNWIN_SENSOR_ID, SENSOR_DRVNAME_OV02A10_SUNWIN, OV02A10_SUNWIN_SensorInit },
#endif
#if defined(OV48B2Q_LUXVISIONS)
{ OV48B2Q_LUXVISIONS_SENSOR_ID, SENSOR_DRVNAME_OV48B2Q_LUXVISIONS, OV48B2Q_LUXVISIONS_SensorInit },
#endif
#if defined(OV16A1Q_OFILM)
{ OV16A1Q_OFILM_SENSOR_ID, SENSOR_DRVNAME_OV16A1Q_OFILM, OV16A1Q_OFILM_SensorInit },
#endif
/*S5K*/
#if defined(S5KJD1_MIPI_RAW)
{S5KJD1_SENSOR_ID, SENSOR_DRVNAME_S5KJD1_MIPI_RAW,
	S5KJD1_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3P9_SUNNY)
    { S5K3P9_SUNNY_SENSOR_ID, SENSOR_DRVNAME_S5K3P9_SUNNY, S5K3P9_SUNNY_SensorInit },
#endif
#if defined(OV23850_MIPI_RAW)
{OV23850_SENSOR_ID, SENSOR_DRVNAME_OV23850_MIPI_RAW,
	OV23850_MIPI_RAW_SensorInit},
#endif
#if defined(OV20880_MIPI_RAW)
{OV20880MIPI_SENSOR_ID, SENSOR_DRVNAME_OV20880_MIPI_RAW,
	OV20880_MIPI_RAW_SensorInit},
#endif
#if defined(OV48B_MIPI_RAW)
{OV48B_SENSOR_ID, SENSOR_DRVNAME_OV48B_MIPI_RAW,
	OV48B_MIPI_RAW_SensorInit},
#endif
#if defined(OV16A10_MIPI_RAW)
{OV16A10_SENSOR_ID, SENSOR_DRVNAME_OV16A10_MIPI_RAW,
	OV16A10_MIPI_RAW_SensorInit},
#endif
#if defined(OV48C_MIPI_RAW)
{OV48C_SENSOR_ID, SENSOR_DRVNAME_OV48C_MIPI_RAW,
	OV48C_MIPI_RAW_SensorInit},
#endif
	/*S5K*/
#if defined(S5K2LQSX_MIPI_RAW)
{S5K2LQSX_SENSOR_ID, SENSOR_DRVNAME_S5K2LQSX_MIPI_RAW,
	S5K2LQSX_MIPI_RAW_SensorInit},
#endif
#if defined(S5K4H7_MIPI_RAW)
{S5K4H7_SENSOR_ID, SENSOR_DRVNAME_S5K4H7_MIPI_RAW, S5K4H7_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3P8SP_MIPI_RAW)
{S5K3P8SP_SENSOR_ID, SENSOR_DRVNAME_S5K3P8SP_MIPI_RAW,
	S5K3P8SP_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3P8SX_MIPI_RAW)
{S5K3P8SX_SENSOR_ID, SENSOR_DRVNAME_S5K3P8SX_MIPI_RAW,
	S5K3P8SX_MIPI_RAW_SensorInit},
#endif
#if defined(S5K4E6_MIPI_RAW)
{S5K4E6_SENSOR_ID, SENSOR_DRVNAME_S5K4E6_MIPI_RAW, S5K4E6_MIPI_RAW_SensorInit},
#endif
#if defined(S5K2L7_MIPI_RAW)
{S5K2L7_SENSOR_ID, SENSOR_DRVNAME_S5K2L7_MIPI_RAW, S5K2L7_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3L8_MIPI_RAW)
{S5K3L8_SENSOR_ID, SENSOR_DRVNAME_S5K3L8_MIPI_RAW, S5K3L8_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3M3_MIPI_RAW)
{S5K3M3_SENSOR_ID, SENSOR_DRVNAME_S5K3M3_MIPI_RAW, S5K3M3_MIPI_RAW_SensorInit},
#endif
#if defined(S5K2P7_MIPI_RAW)
{S5K2P7_SENSOR_ID, SENSOR_DRVNAME_S5K2P7_MIPI_RAW, S5K2P7_MIPI_RAW_SensorInit},
#endif
#if defined(S5K2T7SP_MIPI_RAW)
{S5K2T7SP_SENSOR_ID, SENSOR_DRVNAME_S5K2T7SP_MIPI_RAW,
	S5K2T7SP_MIPI_RAW_SensorInit},
#endif
#if defined(S5K2P8_MIPI_RAW)
{S5K2P8_SENSOR_ID, SENSOR_DRVNAME_S5K2P8_MIPI_RAW, S5K2P8_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3P3SX_MIPI_RAW)
{S5K3P3SX_SENSOR_ID, SENSOR_DRVNAME_S5K3P3SX_MIPI_RAW,
	S5K3P3SX_MIPI_RAW_SensorInit},
#endif
#if defined(S5K2X8_MIPI_RAW)
{S5K2X8_SENSOR_ID, SENSOR_DRVNAME_S5K2X8_MIPI_RAW, S5K2X8_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3M2_MIPI_RAW)
{S5K3M2_SENSOR_ID, SENSOR_DRVNAME_S5K3M2_MIPI_RAW, S5K3M2_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3H2YX_MIPI_RAW)
{S5K3H2YX_SENSOR_ID, SENSOR_DRVNAME_S5K3H2YX_MIPI_RAW,
	S5K3H2YX_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3H7Y_MIPI_RAW)
{S5K3H7Y_SENSOR_ID, SENSOR_DRVNAME_S5K3H7Y_MIPI_RAW,
	S5K3H7Y_MIPI_RAW_SensorInit},
#endif
#if defined(S5K4H5YC_MIPI_RAW)
{S5K4H5YC_SENSOR_ID, SENSOR_DRVNAME_S5K4H5YC_MIPI_RAW,
	S5K4H5YC_MIPI_RAW_SensorInit},
#endif
#if defined(S5K4H5YX_2LANE_MIPI_RAW)
{S5K4H5YX_2LANE_SENSOR_ID, SENSOR_DRVNAME_S5K4H5YX_2LANE_MIPI_RAW,
	S5K4H5YX_2LANE_MIPI_RAW_SensorInit},
#endif
#if defined(S5K5E2YA_MIPI_RAW)
{S5K5E2YA_SENSOR_ID, SENSOR_DRVNAME_S5K5E2YA_MIPI_RAW,
	S5K5E2YA_MIPI_RAW_SensorInit},
#endif
#if defined(S5K5CAGX_YUV)
{S5K5CAGX_SENSOR_ID, SENSOR_DRVNAME_S5K5CAGX_YUV, S5K5CAGX_YUV_SensorInit},
#endif
#if defined(S5K4E1GA_MIPI_RAW)
{S5K4E1GA_SENSOR_ID, SENSOR_DRVNAME_S5K4E1GA_MIPI_RAW,
	S5K4E1GA_MIPI_RAW_SensorInit},
#endif
#if defined(S5K4ECGX_YUV)
{S5K4ECGX_SENSOR_ID, SENSOR_DRVNAME_S5K4ECGX_YUV, S5K4ECGX_YUV_SensorInit},
#endif
#if defined(S5K4ECGX_MIPI_YUV)
{S5K4ECGX_SENSOR_ID, SENSOR_DRVNAME_S5K4ECGX_MIPI_YUV,
	S5K4ECGX_MIPI_YUV_SensorInit},
#endif
#if defined(S5K4ECGX_MIPI_JPG)
{S5K4ECGX_SENSOR_ID, SENSOR_DRVNAME_S5K4ECGX_MIPI_JPG,
	S5K4ECGX_MIPI_JPG_SensorInit},
#endif
#if defined(S5K8AAYX_MIPI_YUV)
{S5K8AAYX_MIPI_SENSOR_ID, SENSOR_DRVNAME_S5K8AAYX_MIPI_YUV,
	S5K8AAYX_MIPI_YUV_SensorInit},
#endif
#if defined(S5K8AAYX_YUV)
{S5K8AAYX_MIPI_SENSOR_ID, SENSOR_DRVNAME_S5K8AAYX_YUV,
	S5K8AAYX_PVI_YUV_SensorInit},
#endif
#if defined(S5K5E8YX_MIPI_RAW)
{S5K5E8YX_SENSOR_ID, SENSOR_DRVNAME_S5K5E8YX_MIPI_RAW,
	S5K5E8YX_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3P9SP_MIPI_RAW)
{S5K3P9SP_SENSOR_ID, SENSOR_DRVNAME_S5K3P9SP_MIPI_RAW,
	S5K3P9SP_MIPI_RAW_SensorInit},
#endif
/*HI*/
#if defined(HI846_OFILM)
{ HI846_OFILM_SENSOR_ID, SENSOR_DRVNAME_HI846_OFILM, HI846_OFILM_SensorInit },
#endif
#if defined(HI846_SUNNY)
{ HI846_SUNNY_SENSOR_ID, SENSOR_DRVNAME_HI846_SUNNY, HI846_SUNNY_SensorInit },
#endif
#if defined(OV8856_FOXCONN)
{ OV8856_FOXCONN_SENSOR_ID, SENSOR_DRVNAME_OV8856_FOXCONN, OV8856_FOXCONN_SensorInit },
#endif
/*MT*/
/*GC*/
#if defined(GC2375_BYD)
	{ GC2375_BYD_SENSOR_ID, SENSOR_DRVNAME_GC2375_BYD, GC2375_BYD_SensorInit },
#endif
/*SP*/
/*SIV*/
/*PAS (PixArt Image)*/
/*Panasoic*/
/*Toshiba*/
/*Others*/

	/*  ADD sensor driver before this line */
	{0, {0}, NULL}, /* end of list */
};

/* e_add new sensor driver here */

