#=============================================================================
#  add new config for devices check
#  add new config for factory cmdline parse
#  add new config for antenna board gpio match
#  add new config for audio match
#=============================================================================

obj-$(CONFIG_HUAWEI_FBE) += file_encry/
obj-$(CONFIG_HW_SECMEM) += secmem/
obj-$(CONFIG_HUAWEI_BB) += kdump/
obj-y += hkip/
obj-$(CONFIG_CONTEXTHUB) += contexthub/
obj-$(CONFIG_HW_PLAT_POWER) += power/
