#
# Makefile
#
# Copyright (c) 2020-2020 Huawei Technologies Co., Ltd.
#
# hwcam cfg makefile
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-y += hwcam_cfgdev.o
obj-y += hwcam_compat32.o
