ccflags-y += -Idrivers/huawei_platform/audio/tfa98xx/inc -DTFA98XX_GIT_VERSIONS=2.19
ccflags-y += -Idrivers/devkit/audiokit/
tfa98xx-objs := src/tfa98xx.o src/tfa_container.o src/tfa_dsp.o src/tfa_init.o
obj-$(CONFIG_TFA98XX) += tfa98xx.o
